spring.application.name=app

server.port=${SERVER_PORT:8081}

# spring.datasource.url=jdbc:postgresql://localhost:5433/farmadocker
# spring.datasource.username=postgres
# spring.datasource.password=123


# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenAPI (springdoc): document only versioned endpoints
springdoc.paths-to-match=/api/v1/**
